apiVersion: v1
kind: ConfigMap
metadata:
  name: payflow-config
  namespace: payflow
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  REDIS_PORT: "6379"
  REDIS_HOST: "redis"
  MONGODB_PORT: "27017"
