apiVersion: v1
kind: Service
metadata:
  name: payflow-api
  namespace: payflow
  labels:
    app: payflow
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: payflow
    component: api
